# Generated by Django 4.2.6 on 2024-01-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Passport', 'Passport'), ('Transportation', 'Transportation'), ('NEB', 'NEB'), ('ward', 'ward'), ('Municipality', 'Municipality'), ('Dist_office', 'Dist_office'), ('HighCourt', 'HighCourt'), ('DistCourt', 'DistCourt')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('methods', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackthonapp.service')),
            ],
        ),
    ]
