# Generated by Django 4.1.3 on 2024-01-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthonapp', '0002_rename_service_service_name_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_name',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
